### PR TITLE
Facebook bindings for MOE

### PR DESCRIPTION
**Pull request by Kromzem**
I just created the Bindings for the latest facebook sdk. I tested it and it looks like it works :D So if you are able to review them and maybe implement them :) I hope i did all right, cause its my first contribution to a project, so sorry if I was doing something wrong :)

### CODE REVIEW

**Comment by TomGrill** [comment]
Great work, I will look into it this weekend.

**Comment by Kromzem** [comment]
Nice thanks :)

**Comment by Kromzem** [comment]
I'm not sure if you looked over the bindings, but I have to say that they will not work as expected :( Maybe they will work, but on my iPhone, the plain implementation in your library brings some strange errors which aren't what they meant to be. The bindings itself are working. I'm also not sure if it is only a problem on my side or not. So if you can give me any feedback in this direction i will be glad to receive it ;)

**Comment by TomGrill** [comment]
Did not have time so far. I will look at it asap. May take a while :(

**Comment by Kromzem** [comment]
Thats no problem :) Found huge issues in the iOS Environment and going to fix these first ;)

**Comment by Kromzem** [comment]
So I fixed the problems :) Login, SilentLogin and Graph is now fully working. I'm not sure about GameRequest because I didn't tested it. But the main functions are working.

**Comment by ruffiely** [comment]
Hey @Kromzem is there a possibility for me to test your pull request without it is merged?

**Comment by Kromzem** [comment]
Hey @ruffiely
Sure it is :) Just clone the forked repository on my profile ;)

**Comment by ruffiely** [comment]
Cool, I forked it and builded the jars added then the jar files as dependencies to my actual project. I could build the ios moe version and run it on my ipad. 
Anyhow as soon as I try to sign in it fails with following exception:

gdx-facebook (1.3.1-SNAPSHOT) 3 Could not load existing accessToken.
/Volumes/SSD/Android/moe-final/moe/natj/natj/src/main/native/natj/ObjCRuntime.mm:1478 WARNING: Binding class refers to class FBSDKAccessToken, but it can not be found. Fallback to indirect super class.
libc++abi.dylib: terminating with uncaught exception of type NSException

Is there any configuration needed?

**Comment by Kromzem** [comment]
Can you please add me in Skype (Name: kromzem) or another platform? It is easier to help you then :)

**Comment by TomGrill** [comment]
I am aware of this thread but I just do not had time yet.

**Comment by Kromzem** [comment]
As I said, thats no problem :)

**Comment by TomGrill** [comment]
Finally I got some time to check your work out. It is not working for me yet.
Can you show me how your IOSMoeLauncher looks like? 

I get a few errors. Will post errors tommorrow, need to go now.

**Comment by Kromzem** [comment]
Sounds like it isn't set up properly :) <br>
So pls have a look at these steps:<br>
https://developers.facebook.com/docs/ios/getting-started/

When it comes to step 5 you simply had to add these lines to your IOSMoeLauncher:
[add to IOSMoeLauncher.txt](https://github.com/TomGrill/gdx-facebook/files/1056927/add.to.IOSMoeLauncher.txt)

**Comment by TomGrill** [comment]
Ok got it going, will test a couple of things and then merge the PR. This xcode stuff is such a pain....

**Pull request merged**
